### ISSUE TITLE
Issue about assert

### ISSUE THREAD

**Issue by LastAncientOne** [tdrussell/stocktwits_analysis#1]
Hi. I am interest in your codes.
I am having issuing about  
assert len(tweets) = len(labels)
                       ^
SyntaxError: invalid syntax

**Comment by LastAncientOne** [comment]
When I tried this way:
tweets = []
labels = []
all_tweets = []
for filename in os.listdir('./data'):
    path = './data/%s' % filename
    with open(path, 'r') as f:
        data = json.load(f)
    all_tweets.extend(map(lambda m: m['body'], data))
    t, l = get_tweets_and_labels(data)
    tweets.extend(t)
    labels.extend(l)
try:
	assert len(tweets) == len(labels)
except: 
	print '%d labeled examples extracted ' % len(tweets)
	print '%d labeled examples extracted ' % len(labels)

Output:
1869 labeled examples extracted 
0 labeled examples extracted 

They both should of be 1869.
Can you help please? I appreciate the help.

**Comment by smbryan** [comment]
That looks like a Python mismatch version to me. What version of python are you using?

**Comment by LastAncientOne** [comment]
Python 2.7 on window 10

**Comment by smbryan** [comment]
Both 'assert' and 'print' are likely to give you issues then. Try the following:
```
try:
assert( len(tweets) == len(labels))
except:
print( '%d labeled examples extracted ' % len(tweets))
print( '%d labeled examples extracted ' % len(labels))
```
Let me know if that resolves your issue.

**Comment by LastAncientOne** [comment]
1869 labeled examples extracted 
0 labeled examples extracted

**Comment by smbryan** [comment]
Let's back up a step. What does your 'get_tweets_and_labels' look like?

**Comment by LastAncientOne** [comment]
get_tweets_and_labels(data)
Out[133]: (<map at 0x1a42b3e4f60>, <map at 0x1a42db7e828>)

Running sentiment prediction is fine.

**Comment by smbryan** [comment]
Can I see your code?

**Comment by LastAncientOne** [comment]
def get_tweets_and_labels(data):
    # filter out messages without a bullish/bearish tag
    data = filter(lambda m: m['entities']['sentiment'] != None, data)
    # get tweets
    tweets = map(lambda m: m['body'], data)
    # get labels
    def create_label(message):
        sentiment = message['entities']['sentiment']['basic']
        if sentiment == 'Bearish':
            return 0
        elif sentiment == 'Bullish':
            return 1
        else:
            raise Exception('Got unexpected sentiment')
    labels = map(create_label, data)
    return tweets, labels

**Comment by smbryan** [comment]
Okay. Lets go through the basics. Is "def create_labels..." to "raise
Expectation" indented?

**Comment by LastAncientOne** [comment]
Yes is indent.

**Comment by LastAncientOne** [comment]
I am going to tired to run it on my laptop.

**Comment by LastAncientOne** [comment]
Why am I getting error?
Getting tweets for symbol AAPL
b'{"response":{"status":429},"errors":[{"message":"Rate limit exceeded. Client may not make more than 200 requests an hour."}]}'
Error, an API query timed out
-----------------------------
Done
Getting tweets for symbol TSLA
b'{"response":{"status":429},"errors":[{"message":"Rate limit exceeded. Client may not make more than 200 requests an hour."}]}'
Error, an API query timed out
-----------------------------
Done
Getting tweets for symbol AMD
b'{"response":{"status":429},"errors":[{"message":"Rate limit exceeded. Client may not make more than 200 requests an hour."}]}'
Error, an API query timed out
-----------------------------
Done

**Comment by LastAncientOne** [comment]
sorry about the bold font

**Comment by smbryan** [comment]
No worries. Those are messages from the StockTwits API. You've exceeded the
maximum amount of queries for the hour.

**Comment by LastAncientOne** [comment]
I have quick question. Is there a way you can get unlimited requests more than 200?

**Comment by smbryan** [comment]
You'd have to talk to StockTwits. You've maximized what they allow us to do.
